cmake_minimum_required(VERSION 3.13)

project(MetalTranslate)

include(ExternalProject)

set(EXTERNAL_INSTALL_LOCATION ${CMAKE_BINARY_DIR}/external)

if(APPLE)
    # Set ICU root directory (where Homebrew installed ICU)
    execute_process(
        COMMAND brew --prefix icu4c
        OUTPUT_VARIABLE ICU_ROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    # Manually specify the include and library directories for ICU
    set(ICU_INCLUDE_DIR ${ICU_ROOT}/include)
    set(ICU_LIBRARY_DIR ${ICU_ROOT}/lib)
    
    # Find and link ICU
    include_directories(${ICU_INCLUDE_DIR})
    find_package(ICU REQUIRED COMPONENTS uc i18n data)

    # Execute brew command to get the ONEDNN_ROOT
    execute_process(
        COMMAND brew --prefix onednn
        OUTPUT_VARIABLE ONEDNN_ROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    # Include oneDNN directory and library
    include_directories(${ONEDNN_ROOT}/include)
elseif(UNIX)
    # find libdnnl.so
    execute_process(
        COMMAND dpkg --listfiles libdnnl-dev
        COMMAND grep libdnnl.so
        OUTPUT_VARIABLE LIBDNNL_SO
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
endif()

if(APPLE)
    ExternalProject_Add(CTranslate2
        PREFIX third_party/CTranslate2
        GIT_REPOSITORY https://github.com/OpenNMT/CTranslate2
        GIT_TAG v4.3.1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION} -DWITH_MKL=OFF -DWITH_DNNL=ON -DOPENMP_RUNTIME=NONE
        INSTALL_RPATH "@loader_path"
        BUILD_WITH_INSTALL_RPATH TRUE
    )
elseif(UNIX)
    ExternalProject_Add(CTranslate2
        PREFIX third_party/CTranslate2
        GIT_REPOSITORY https://github.com/OpenNMT/CTranslate2
        GIT_TAG v4.3.1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION} -DWITH_MKL=OFF -DWITH_DNNL=ON -DOPENMP_RUNTIME=NONE
        INSTALL_RPATH "$$ORIGIN"
        BUILD_WITH_INSTALL_RPATH TRUE
    )
else()
    ExternalProject_Add(CTranslate2
        PREFIX third_party/CTranslate2
        GIT_REPOSITORY https://github.com/OpenNMT/CTranslate2
        GIT_TAG v4.3.1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION} -DWITH_MKL=OFF -DMKL_CBWR=COMPATIBLE -DWITH_DNNL=ON -DOPENMP_RUNTIME=COMP
    )
endif()

if(UNIX)
    ExternalProject_Add(Tokenizer
        PREFIX third_party/Tokenizer
        GIT_REPOSITORY https://github.com/OpenNMT/Tokenizer
        GIT_TAG v1.37.1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}
        -DCMAKE_CXX_FLAGS="-Wno-enum-constexpr-conversion"
        CXX_STANDARD 11
    )
else()
    ExternalProject_Add(Tokenizer
        PREFIX third_party/Tokenizer
        GIT_REPOSITORY https://github.com/OpenNMT/Tokenizer
        GIT_TAG v1.37.1
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}
        CXX_STANDARD 11
    )
endif()

include_directories(${EXTERNAL_INSTALL_LOCATION}/include)
link_directories(${EXTERNAL_INSTALL_LOCATION}/lib)

add_library(metaltranslate SHARED
    src/MetalTranslate.cpp
    src/metal_api.cpp
)

target_include_directories(metaltranslate PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/src
    ${EXTERNAL_INSTALL_LOCATION}/include
)

# target_compile_definitions(metaltranslate PRIVATE METALTRANSLATE_EXPORTS)
add_dependencies(metaltranslate CTranslate2 Tokenizer)

if(WIN32)
    add_definitions(-DMETALTRANSLATE_EXPORTS)
endif()

message("DIRS: ")
message(STATUS "${EXTERNAL_INSTALL_LOCATION}")
message(STATUS "${CMAKE_CURRENT_BINARY_DIR}")
message(STATUS "${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS "${LIBDNNL_SO}")

target_link_libraries(metaltranslate PRIVATE ctranslate2 OpenNMTTokenizer)

# Ensure rpath is set to include the directory where dependencies will be located
if(APPLE)
    set_target_properties(metaltranslate PROPERTIES
        CXX_EXTENSIONS NO
        CXX_STANDARD 17
        RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
        INSTALL_RPATH "@loader_path"
        BUILD_WITH_INSTALL_RPATH TRUE
    )
elseif(UNIX)
    set_target_properties(metaltranslate PROPERTIES
        CXX_EXTENSIONS NO
        CXX_STANDARD 17
        RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
        INSTALL_RPATH "$ORIGIN"
        BUILD_WITH_INSTALL_RPATH TRUE
    )
else()
    set_target_properties(metaltranslate PROPERTIES
        CXX_EXTENSIONS NO
        CXX_STANDARD 17
        RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
    )
endif()

if(APPLE)
    # Set RPATH for all binaries
    set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
    list(APPEND CMAKE_INSTALL_RPATH "@loader_path")
endif()

# TODO: find a better way to get these libraries version number (they can change between builds)
if(APPLE)
    # Copy required dylibs to the build directory and adjust LC_LOAD_DYLIB path
    add_custom_command(TARGET metaltranslate POST_BUILD
        COMMAND bash -c "
        ICU_UC_LIB_NAME=$(otool -L ${EXTERNAL_INSTALL_LOCATION}/lib/libOpenNMTTokenizer.dylib | grep 'libicuuc' | sed -E 's|.*(libicuuc[^ ]*).*|\\1|');
        ICU_DATA_LIB_NAME=$(otool -L ${EXTERNAL_INSTALL_LOCATION}/lib/libOpenNMTTokenizer.dylib | grep 'libicudata' | sed -E 's|.*(libicudata[^ ]*).*|\\1|');
        DNNL_LIB_NAME=$(otool -L ${EXTERNAL_INSTALL_LOCATION}/lib/libctranslate2.4.3.1.dylib | grep 'libdnnl' | sed -E 's|.*(libdnnl[^ ]*).*|\\1|');

        echo 'Extracted ICU UC library name: ${ICU_UC_LIB_NAME}';
        echo 'Extracted ICU DATA library name: ${ICU_DATA_LIB_NAME}';
        echo 'Extracted DNNL library name: ${DNNL_LIB_NAME}';


        install_name_tool -change ${ONEDNN_ROOT}/lib/${DNNL_LIB_NAME} @rpath/libdnnl.3.dylib ${EXTERNAL_INSTALL_LOCATION}/lib/libctranslate2.4.3.1.dylib # change lib path of ctranslate2 lib
        install_name_tool -change ${ICU_LIBRARY_DIR}/${ICU_UC_LIB_NAME} @rpath/libicuuc.dylib ${EXTERNAL_INSTALL_LOCATION}/lib/libctranslate2.4.3.1.dylib
        install_name_tool -change ${ICU_LIBRARY_DIR}/${ICU_DATA_LIB_NAME} @rpath/libicudata.dylib ${EXTERNAL_INSTALL_LOCATION}/lib/libOpenNMTTokenizer.dylib
        install_name_tool -change ${ICU_LIBRARY_DIR}/${ICU_UC_LIB_NAME} @rpath/libicuuc.dylib ${EXTERNAL_INSTALL_LOCATION}/lib/libOpenNMTTokenizer.dylib

        # copy files to build directory
        ${CMAKE_COMMAND} -E copy ${ONEDNN_ROOT}/lib/libdnnl.3.dylib $<TARGET_FILE_DIR:metaltranslate>
        ${CMAKE_COMMAND} -E copy ${ICU_LIBRARY_DIR}/libicuuc.dylib $<TARGET_FILE_DIR:metaltranslate>
        ${CMAKE_COMMAND} -E copy ${ICU_LIBRARY_DIR}/libicudata.dylib $<TARGET_FILE_DIR:metaltranslate>
        
        "
        COMMENT "Adjusting LC_LOAD_DYLIB path for libdnnl"
    )
elseif(UNIX)
    add_custom_command(TARGET metaltranslate POST_BUILD

        COMMAND ${CMAKE_COMMAND} -E copy ${EXTERNAL_INSTALL_LOCATION}/lib/libctranslate2.so $<TARGET_FILE_DIR:metaltranslate>/libctranslate2.so
        COMMAND ${CMAKE_COMMAND} -E copy ${EXTERNAL_INSTALL_LOCATION}/lib/libOpenNMTTokenizer.so $<TARGET_FILE_DIR:metaltranslate>
        COMMAND ${CMAKE_COMMAND} -E copy ${LIBDNNL_SO} $<TARGET_FILE_DIR:metaltranslate>

        COMMAND patchelf --replace-needed libdnnl.so.3 '$$ORIGIN/libdnnl.so' ${CMAKE_CURRENT_BINARY_DIR}/libctranslate2.so
        COMMAND patchelf --replace-needed libctranslate2.so.4 'libctranslate2.so' ${CMAKE_CURRENT_BINARY_DIR}/libmetaltranslate.so
        COMMENT "Adjusting ctranslate2 rpath and copying shared objects"
    )
else()
    add_custom_command(TARGET metaltranslate POST_BUILD

        # Check permissions of the target directory
        COMMAND ${CMAKE_COMMAND} -E echo "Checking permissions of target directory:"
        COMMAND ${CMAKE_COMMAND} -E echo "Directory: $<TARGET_FILE_DIR:metaltranslate>"
        COMMAND ${CMAKE_COMMAND} -E chdir $<TARGET_FILE_DIR:metaltranslate> ${CMAKE_COMMAND} -E echo *

        # Copy runtime DLLs
        COMMAND ${CMAKE_COMMAND} -E copy -t $<TARGET_FILE_DIR:metaltranslate> $<TARGET_RUNTIME_DLLS:metaltranslate>

        # List contents of the target directory after copying
        COMMAND ${CMAKE_COMMAND} -E echo "Contents of target directory after copy:"
        COMMAND ${CMAKE_COMMAND} -E chdir $<TARGET_FILE_DIR:metaltranslate> ${CMAKE_COMMAND} -E echo *

        COMMAND_EXPAND_LISTS
    )
endif()
